### ISSUE TITLE
Fixing checkboxes in comment subcription form

### ISSUE THREAD

**Issue by 2ndkauboy** [wceu/wceu-2020#5]
Example page: https://2020.europe.wordcamp.org/2019/12/29/contributor-day/

![image](https://user-images.githubusercontent.com/1793177/72543569-3db0ee00-3886-11ea-9549-83b9d1858ede.png)

Tested on: Chrome 79 on Manjaro Linux

Adding this would fix the issue:

```css
.comment-subscription-form input[type="checkbox"] {
    -webkit-appearance: unset !important;
}
```
